import { Opportunity } from '../types';

export const MOCK_OPPORTUNITIES: Opportunity[] = [
  {
    id: '1',
    title: 'Google Software Engineering Internship 2026',
    category: 'Internships',
    organization: 'Google',
    location: 'Mountain View, CA',
    deadline: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    applyLink: 'https://google.com/careers',
    description: 'Join Google for a summer of innovation and learning. Work on real-world projects that impact billions of users. This internship is designed for students who are passionate about computer science and want to gain practical experience in a fast-paced environment.',
    shortDescription: 'Software engineering internship at Google for 2026.',
    postedDate: new Date().toISOString(),
    type: 'Hybrid',
    field: 'Technology',
    tags: ['AI', 'Software Development', 'Startup'],
    views: 1250,
    isPinned: true,
    isApproved: true,
    duration: '12 weeks',
    eligibility: 'Current university student in CS or related field',
    featuredImageUrl: 'https://storage.googleapis.com/dala-prod-public-storage/generated-images/018564a2-3c2e-49e4-b8cf-a7247087d862/internship-background-cb2e3960-1773569301195.webp'
  },
  {
    id: '2',
    title: 'World Economic Forum 2025: Global Leaders Summit',
    category: 'Conferences',
    organization: 'WEF',
    location: 'Davos, Switzerland',
    deadline: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    applyLink: 'https://weforum.org',
    description: 'The annual meeting of the World Economic Forum brings together global leaders to discuss the most pressing issues. The theme for 2025 focuses on "Rebuilding Trust" in a fragmented world.',
    shortDescription: 'Global leadership conference in Switzerland focusing on international cooperation.',
    postedDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    type: 'Onsite',
    field: 'Business',
    tags: ['Economy', 'Leadership', 'Networking'],
    views: 850,
    isApproved: true,
    eventDate: 'January 15-19, 2025',
    organizer: 'World Economic Forum',
    featuredImageUrl: 'https://storage.googleapis.com/dala-prod-public-storage/generated-images/018564a2-3c2e-49e4-b8cf-a7247087d862/conference-background-4dfeeed8-1773569301157.webp'
  },
  {
    id: '3',
    title: 'Microsoft Research PhD Fellowship',
    category: 'Fellowships',
    organization: 'Microsoft Research',
    location: 'Remote',
    deadline: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000).toISOString(),
    applyLink: 'https://microsoft.com/research',
    description: 'A prestigious fellowship program for PhD students pursuing research in computer science and related fields. Provides funding for two years and opportunities for mentorship.',
    shortDescription: 'Research fellowship for PhD students with full funding and mentorship.',
    postedDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    type: 'Remote',
    field: 'Research',
    tags: ['AI', 'Computer Science', 'Innovation'],
    views: 620,
    isApproved: true,
    featuredImageUrl: 'https://storage.googleapis.com/dala-prod-public-storage/generated-images/018564a2-3c2e-49e4-b8cf-a7247087d862/tech-opportunity-background-08b66a88-1773569300809.webp'
  },
  {
    id: '4',
    title: 'Harvard University Financial Aid Scholarship 2025',
    category: 'Scholarships',
    organization: 'Harvard University',
    location: 'Cambridge, MA',
    deadline: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    applyLink: 'https://harvard.edu/scholarships',
    description: 'Full-ride scholarships for outstanding international students applying for undergraduate programs. Includes tuition, room, and board.',
    shortDescription: 'Full-ride undergraduate scholarship for international students.',
    postedDate: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    type: 'Onsite',
    field: 'Research',
    tags: ['Education', 'Financial Aid'],
    views: 2100,
    isApproved: true,
    featuredImageUrl: 'https://storage.googleapis.com/dala-prod-public-storage/generated-images/018564a2-3c2e-49e4-b8cf-a7247087d862/scholarship-background-2e6fe150-1773569301410.webp'
  },
  {
    id: '5',
    title: 'Global Tech Hackathon: AI for Good',
    category: 'Competitions',
    organization: 'Tech-X',
    location: 'Remote',
    deadline: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
    applyLink: 'https://techx-hack.com',
    description: 'Build the next generation of AI tools in 48 hours. $50,000 in prizes and mentorship opportunities from industry leaders.',
    shortDescription: '48-hour global AI hackathon with significant prizes.',
    postedDate: new Date().toISOString(),
    type: 'Remote',
    field: 'Technology',
    tags: ['AI', 'Entrepreneurship', 'Startup'],
    views: 450,
    isApproved: true
  },
  {
    id: '6',
    title: 'Senior Product Designer',
    category: 'Jobs',
    organization: 'Airbnb',
    location: 'San Francisco, CA',
    deadline: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000).toISOString(),
    applyLink: 'https://airbnb.com/careers',
    description: 'Lead the design of core Airbnb experiences. Looking for a designer with 5+ years of experience in product design and user research.',
    shortDescription: 'Senior design role at a leading travel platform.',
    postedDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    type: 'Hybrid',
    field: 'Design',
    tags: ['UX', 'UI', 'Product Design'],
    views: 940,
    isApproved: true
  },
  {
    id: '7',
    title: 'UNICEF Social Impact Grant',
    category: 'Grants',
    organization: 'UNICEF',
    location: 'Global',
    deadline: new Date(Date.now() + 45 * 24 * 60 * 60 * 1000).toISOString(),
    applyLink: 'https://unicef.org/grants',
    description: 'Funding for startups and non-profits working on educational technology for children in developing regions.',
    shortDescription: 'Up to $100k in funding for social impact projects.',
    postedDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    type: 'Remote',
    field: 'Business',
    tags: ['Social Impact', 'Education', 'Non-profit'],
    views: 1100,
    isApproved: true
  },
  {
    id: '8',
    title: '[PENDING] Tesla Engineering Workshop',
    category: 'Events',
    organization: 'Tesla',
    location: 'Austin, TX',
    deadline: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(),
    applyLink: 'https://tesla.com/events',
    description: 'A hands-on workshop with Tesla engineers to learn about the future of energy and manufacturing.',
    shortDescription: 'Engineering workshop at Tesla Giga Texas.',
    postedDate: new Date().toISOString(),
    type: 'Onsite',
    field: 'Engineering',
    tags: ['Energy', 'Manufacturing', 'Tesla'],
    views: 200,
    isApproved: false
  }
];